//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SatisfactoryOverlay.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SatisfactoryOverlay.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon app {
            get {
                object obj = ResourceManager.GetObject("app", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Button_Connect {
            get {
                return ResourceManager.GetString("Button_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in browser.
        /// </summary>
        public static string Button_OpenUpdate {
            get {
                return ResourceManager.GetString("Button_OpenUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Button_SelectOutputFile {
            get {
                return ResourceManager.GetString("Button_SelectOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start output.
        /// </summary>
        public static string Button_SetOutputFile {
            get {
                return ResourceManager.GetString("Button_SetOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mods.
        /// </summary>
        public static string CheckBox_Modlist {
            get {
                return ResourceManager.GetString("CheckBox_Modlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playtime (selected save).
        /// </summary>
        public static string CheckBox_Playtime {
            get {
                return ResourceManager.GetString("CheckBox_Playtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session name.
        /// </summary>
        public static string CheckBox_SessionName {
            get {
                return ResourceManager.GetString("CheckBox_SessionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting area.
        /// </summary>
        public static string CheckBox_StartingArea {
            get {
                return ResourceManager.GetString("CheckBox_StartingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playtime (total).
        /// </summary>
        public static string CheckBox_TotalPlaytime {
            get {
                return ResourceManager.GetString("CheckBox_TotalPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CloseSolution_16x {
            get {
                object obj = ResourceManager.GetObject("CloseSolution_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text File.
        /// </summary>
        public static string Enum_Output_File {
            get {
                return ResourceManager.GetString("Enum_Output_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StreamlabsOBS.
        /// </summary>
        public static string Enum_Output_Streamlabs {
            get {
                return ResourceManager.GetString("Enum_Output_Streamlabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OBS Studio.
        /// </summary>
        public static string Enum_Output_Studio {
            get {
                return ResourceManager.GetString("Enum_Output_Studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_de {
            get {
                object obj = ResourceManager.GetObject("flag_de", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap flag_en {
            get {
                object obj = ResourceManager.GetObject("flag_en", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed Info.
        /// </summary>
        public static string Header_DisplayedInfo {
            get {
                return ResourceManager.GetString("Header_DisplayedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Label_CloseApplication {
            get {
                return ResourceManager.GetString("Label_CloseApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Label_Locale {
            get {
                return ResourceManager.GetString("Label_Locale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        public static string Label_LocaleDE {
            get {
                return ResourceManager.GetString("Label_LocaleDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Label_LocaleEN {
            get {
                return ResourceManager.GetString("Label_LocaleEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of &apos;Text (GDI+)&apos; source in OBS.
        /// </summary>
        public static string Label_ObsElement {
            get {
                return ResourceManager.GetString("Label_ObsElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP of PC running OBS.
        /// </summary>
        public static string Label_ObsIp {
            get {
                return ResourceManager.GetString("Label_ObsIp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 127.0.0.1 for local PC.
        /// </summary>
        public static string Label_ObsIpHint {
            get {
                return ResourceManager.GetString("Label_ObsIpHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Label_ObsPort {
            get {
                return ResourceManager.GetString("Label_ObsPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output File.
        /// </summary>
        public static string Label_OutputFile {
            get {
                return ResourceManager.GetString("Label_OutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playtime.
        /// </summary>
        public static string Label_Playtime {
            get {
                return ResourceManager.GetString("Label_Playtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session / Savegame.
        /// </summary>
        public static string Label_SessionSelect {
            get {
                return ResourceManager.GetString("Label_SessionSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show settings.
        /// </summary>
        public static string Label_ShowSettings {
            get {
                return ResourceManager.GetString("Label_ShowSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to API Token.
        /// </summary>
        public static string Label_StreamlabsToken {
            get {
                return ResourceManager.GetString("Label_StreamlabsToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Streaming application.
        /// </summary>
        public static string Label_Streamtool {
            get {
                return ResourceManager.GetString("Label_Streamtool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Websocket password.
        /// </summary>
        public static string Label_StudioPassword {
            get {
                return ResourceManager.GetString("Label_StudioPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total playtime.
        /// </summary>
        public static string Label_TotalPlaytime {
            get {
                return ResourceManager.GetString("Label_TotalPlaytime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Localize_16x {
            get {
                object obj = ResourceManager.GetObject("Localize_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connected.
        /// </summary>
        public static string Message_Connected {
            get {
                return ResourceManager.GetString("Message_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disconnected.
        /// </summary>
        public static string Message_Disconnected {
            get {
                return ResourceManager.GetString("Message_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Satisfactory savegame folder does not exist or contains no savegames. Application will close now..
        /// </summary>
        public static string Message_SavegameError {
            get {
                return ResourceManager.GetString("Message_SavegameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No savegames found.
        /// </summary>
        public static string Message_SavegameErrorTitle {
            get {
                return ResourceManager.GetString("Message_SavegameErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more than one valid subdirectories in the savegame folder. If some of them are your personal backups, please move them to another location..
        /// </summary>
        public static string Message_TooManySavegameFolders {
            get {
                return ResourceManager.GetString("Message_TooManySavegameFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid structure of savegame folder.
        /// </summary>
        public static string Message_TooManySavegameFoldersTitle {
            get {
                return ResourceManager.GetString("Message_TooManySavegameFoldersTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a new version ready for download.
        /// </summary>
        public static string Message_UpdateAvailable {
            get {
                return ResourceManager.GetString("Message_UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ShowDetailsPane_16x {
            get {
                object obj = ResourceManager.GetObject("ShowDetailsPane_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available.
        /// </summary>
        public static string Word_Available {
            get {
                return ResourceManager.GetString("Word_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Word_Version {
            get {
                return ResourceManager.GetString("Word_Version", resourceCulture);
            }
        }
    }
}
